#include "TH1F.h"
#include "TRandom.h"
#include <math.h>

void genGauss()
{
    TH1F* h = new TH1F("hGauss", "Gaussian distribution from MC", 100, -2., 2.);
    TH1F* g = new TH1F("gGauss", "Gaussian distribution from ROOT", 100, -2., 2.);

    float x,y;
    float x_1; //

    // Parameters of the gaussian
    float x_0 = 0.;
    float sigma = 1.;
    float F = 1/sqrt(2*M_PI*sigma); // Maximum

    // Variables for the computation of the area under the gaussian
    float area = 0.;
    int counter = 0;

    // Draw 10000 numbers according the gaussian law
    // We use gRandom->Uniform(MAX)  to draw numbers
    // uniformly  between  0. and MAX
    for (int i=0; i<10000; i++) {
        y = gRandom->Uniform(1);
        x = gRandom->Uniform(4) -2;
        if (y < ROOT::Math::gaussian_pdf(x,sigma,x_0)/F) {
            // we  fill here the histogram h
            h->Fill(x);

            // and we fill the histogram g
            // inside the if to get the same number of events
            x_1 = gRandom->Gaus(x_0,sigma);
            g->Fill(x_1);

            // Computation of the Area
            // for 3 sigma
            counter = counter +1; // for the normalisation
            if ( abs(x) > 3*sigma) {
                area = area + 1.;
            }
        }
    }

    cout << "Area under the gaussian (under the tails at 3 sigma) : " << area/counter << endl;

    // we plot the histogram from MC in ROOT
    h->Draw();
    h->Fit("gaus");

    // we plot a gaussian distribution generated by ROOT with the same parameters
    g->SetLineColor(8);
    g->Draw("SAME");
    g->Fit("gaus");
}
